### ISSUE TITLE
.env file not being loaded

### ISSUE THREAD

**Issue by ryancwalsh** [TwilioDevEd/appointment-reminders-laravel#2]
Hi, I've been spending hours on this and haven't figured out how to get this sample app running.  I am very interested in Twilio, but so far it isn't as easy as I'd hoped.

I cloned this repo to my Windows 10 machine and (using Git Bash) ran `composer update` and `composer install` and editing my `.env` file and ran this and got this error:

```
php artisan migrate
PHP Fatal error:  Uncaught RuntimeException: Required environment variable missing, or value not allowed: 'TWILIO_ACCOUNT_SID', 'TWILIO_AUTH_TOKEN', 'TWILIO_SENDING_NUMBER' in F:\code\Twilio\appointment-reminders-laravel\vendor\vlucas\phpdotenv\src\Dotenv.php:122
```

From various debugging, I've figured out that my .env file is never being loaded.

Do you have any ideas what the problem might be?  I appreciate your help.

**Comment by ryancwalsh** [comment]
Ahhh, I just saw a recent commit of yours.  When I revert https://github.com/TwilioDevEd/appointment-reminders-laravel/commit/4d7a18f22b495fdd6d6dbaeb41d44f3a4a3d6e1b, the .env seems to load for me, and now the error that I'm getting is `[InvalidArgumentException]   Database [] not configured.`, so now I'll try to figure out why.

**Comment by ryancwalsh** [comment]
After setting `DB_CONNECTION=mysql` and using the hints at http://stackoverflow.com/a/31513179/470749 (which you might want to put in your readme, especially the `php artisan key:generate`), I think it might be working!  At least I see a webpage in the browser.

**Comment by nebtrx** [comment]
Hi @ryancwalsh. You should try sourcing your env vars. Also take into account that you should replace your Twilio related env vars with real values, I mean, use your test/real credentials from Twilio, otherwise it will fail silently. Good look and success

**Comment by ryancwalsh** [comment]
Thanks for the response, @nebtrx .  By doing what I mentioned above (including revert https://github.com/TwilioDevEd/appointment-reminders-laravel/commit/4d7a18f22b495fdd6d6dbaeb41d44f3a4a3d6e1b) and also adding `private $appointments = array();`, which seemed to be missing from `class AppointmentReminder`, and also handling the craziness with the chained certificates problem by downloading cacert.pem and changing my php.ini, it works!  Thanks for the demo app.  You might want to add documentation about everything I just experienced so that other people don't spend hours frustrated on this like I did.

**Comment by mcelicalderon** [comment]
@ryancwalsh Thanks for the feedback! I have updated the app (something like reverting [4d7a18f](https://github.com/TwilioDevEd/appointment-reminders-laravel/commit/4d7a18f22b495fdd6d6dbaeb41d44f3a4a3d6e1b)) so you don't get an error when performing artisan tasks and installing dependencies. I will also update the readme file to include more steps in order to run the app.

**Comment by Thomasosho** [comment]
Hi, how do i write a cronjob command to run my artisan command?
