### ISSUE TITLE
Will be a compatible version for Laravel 4.x ?

### ISSUE THREAD

**Issue by SwiTool** [TwilioDevEd/appointment-reminders-laravel#3]
Hi,

i'm wondering if this can be dragged out to work with Laravel 4.x, and if it's not, is there any planned devs for this version ?

Thank you.

**Comment by mcelicalderon** [comment]
@SwiTool As this is just an example application we do not plan to support different Laravel versions. If you are using part of this code in an existing Laravel 4.x application you should be able to copy the Twilio relevant parts to make it work. Let us know if you have any other questions.
