### ISSUE TITLE
Artisan Error

### ISSUE THREAD

**Issue by shah0150** [TwilioDevEd/appointment-reminders-laravel#4]
Hello, Thank you for this wonderful app. 

I tried deploying this app on Heroku and it didn't work Run scripts & scale dynos it just got stucked over here. 

Secondly, i tried to run this locally and it showed me the error too : 

Adeshs-MacBook-Pro:appointment adeshshah$ php artisan migrate

Warning: require(/Applications/MAMP/htdocs/appointment/bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in /Applications/MAMP/htdocs/appointment/bootstrap/autoload.php on line 17

Fatal error: require(): Failed opening required '/Applications/MAMP/htdocs/appointment/bootstrap/../vendor/autoload.php' (include_path='.:') in /Applications/MAMP/htdocs/appointment/bootstrap/autoload.php on line 17
Adeshs-MacBook-Pro:appointment adeshshah$ 

Please help me resolve this issue. 

Thank you,
Adesh

**Comment by mcelicalderon** [comment]
Hello @shah0150 ! I did find an error while trying to run this app from scratch. I wouldn't allow you to install dependencies with composer unless you manually exported the required environment variables. I have fixed this and now it should work after running `composer install` and copying the .env.example file to .env remember to edit this `.env` file to match your configuration.

Regarding the heroku deployment, we have stopped to support this feature in latest application examples. This is something we won't spend much time trying to fix in existing applications.

Let me know if you have any other problem trying to run the app locally. Also, remember to run `php artisan key:generate` after you copy the .env file. I'll update the readme file to add more steps
